### ISSUE TITLE
no replies (just white boxes)

### ISSUE THREAD

**Issue by thoschi** [mtopolnik/Assistant#1]
A wonderul project idea - same as simple as helpful!

Installed it under /e/os and I can use DALL-E for creating images.
But ChatGPT is not replying - all I get are white boxes as reply to my (correctly understood) input.

Any hints?

Best regards
thoschi

**Comment by mtopolnik** [comment]
Sorry, haven't seen this issue opened... occasionally this happens to me, probably overload on OpenAI side. But if it's permanent, I would have to investigate what theoretical options are possible. There's generally not much to blame, if you're getting through to Dall-E, that means the API key is working.

**Comment by thoschi** [comment]
I doubt that this is really the problem.

Whenever I tried (and I tried it often) there is always a white box as a reply. Using the ChatGPT web interface at the same time works fine.

**Comment by thoschi** [comment]
I even tried to use ChatGPT from Python via the API - and this works fine too. So I think it has to be something else...

**Comment by mtopolnik** [comment]
Since I use it successfully every day, it's really hard to guess. Do you have the latest version?
